-- Importacao em massa: Carteira Xeque Mate (792 clientes)
-- Gerado a partir do PDF fornecido pelo usuario. Rode no SQL Editor do Supabase.

-- 1) Permitir o novo valor 'cancelado' em financeiro_status
alter table clientes drop constraint if exists clientes_financeiro_status_check;
alter table clientes add constraint clientes_financeiro_status_check check (financeiro_status in ('em_dia', 'atrasado', 'inadimplente', 'cancelado'));

-- 2) Garantir que a equipe existe
insert into equipe (nome) select v.nome from (values ('Gabriel'), ('Thamires'), ('Cley')) as v(nome) where not exists (select 1 from equipe e where e.nome = v.nome);

-- 3) Importar os 792 clientes da carteira
with resp as (
  select id, nome from equipe where nome in ('Gabriel', 'Thamires', 'Cley')
)
insert into clientes (nome, grupo, cota, responsavel_id, financeiro_status)
select v.nome, v.grupo, v.cota, resp.id, v.status
from (values
  ('PROSPERINO VAZ VIEIRA SOBRINHO', '617', '1759', 'inadimplente', 'Gabriel'),
  ('LAVOARZIER  RIBEIRO DE OLIVEIRA', '704', '354', 'inadimplente', 'Gabriel'),
  ('MAURÍCIO MARINHO', '704', '1442', 'inadimplente', 'Gabriel'),
  ('JUCIMAR FERNANDES OLIVEIRA', '704', '615', 'inadimplente', 'Gabriel'),
  ('JOCIMAR COSTA DA CONCEICAO', '704', '176', 'inadimplente', 'Gabriel'),
  ('MARCELO CAMPOS MACHADO', '618', '8870', 'inadimplente', 'Gabriel'),
  ('LUCAS DE SOUZA RIBEIRO SOARES', '617', '2091', 'inadimplente', 'Gabriel'),
  ('CAIQUE LUIS RISSA SAHION', '616', '969', 'inadimplente', 'Gabriel'),
  ('MARCIA CAITANO LIMA DA SILVA', '617', '3264', 'inadimplente', 'Gabriel'),
  ('LAERT CLEBSON MACHADO DE BARROS BATISTA SILVA DO NASCIMENTO', '616', '1273', 'inadimplente', 'Gabriel'),
  ('CAROLINA DE MOURA LOURO', '616', '1219', 'inadimplente', 'Gabriel'),
  ('JERFFERSON PLINIO ARAUJO DOS SANTOS', '617', '3179', 'inadimplente', 'Gabriel'),
  ('CELSO GALAMBA', '618', '3798', 'inadimplente', 'Gabriel'),
  ('CARLOS HENRIQUE GONÇALVES MAIA', '535', '2722', 'inadimplente', 'Gabriel'),
  ('VANESSA FERREIRA SILVA PORTO', '540', '393', 'inadimplente', 'Gabriel'),
  ('ROGERIO ANTONIO AMADEU', '529', '4338', 'inadimplente', 'Gabriel'),
  ('WAGNER LEAL DA PAIXÃO', '5000', '6487', 'inadimplente', 'Gabriel'),
  ('ELY BETECEL DA COSTA', '541', '391', 'inadimplente', 'Gabriel'),
  ('ADRIANO MORAES DE OLIVEIRA', '617', '5545', 'inadimplente', 'Gabriel'),
  ('RODRIGO LUIZ BATISTA DE OLIVEIRA', '616', '49', 'inadimplente', 'Gabriel'),
  ('BRUNO RAPHAEL DE SOUZA NANTES', '618', '928', 'inadimplente', 'Gabriel'),
  ('MARCOS ANTONIO DA SILVA', '617', '2406', 'inadimplente', 'Gabriel'),
  ('FERNANDO CUNHA DE OLIVEIRA', '617', '5754', 'inadimplente', 'Gabriel'),
  ('FRANCISCO DAS CHAGAS OLIVEIRA DE AGUIAR', '616', '1431', 'inadimplente', 'Gabriel'),
  ('CELSO APARECIDO DOS REIS', '529', '8156', 'inadimplente', 'Gabriel'),
  ('JOSE RIBAMAR SERVILHO SILVA', '617', '5591', 'inadimplente', 'Gabriel'),
  ('ANDRE JOSE TIAGO VIEIRA DE OLIVEIRA', '617', '3833', 'inadimplente', 'Gabriel'),
  ('CÍCERO BORGES VIEIRA', '617', '7743', 'inadimplente', 'Gabriel'),
  ('ANTONIO CLAUDIO RIBEIRO DA SILVA', '617', '8033', 'inadimplente', 'Gabriel'),
  ('JÚLIO CESAR FELIX DA SILVA', '5000', '4185', 'inadimplente', 'Gabriel'),
  ('ANDRE JANDT', '540', '365', 'inadimplente', 'Gabriel'),
  ('NILTON DO NASCIMENTO RODRIGUES', '617', '3352', 'inadimplente', 'Gabriel'),
  ('DIEGO APARECIDO MARTINS DOS SANTOS', '617', '4747', 'inadimplente', 'Gabriel'),
  ('Gustavo naian campos Delgado', '618', '1939', 'inadimplente', 'Gabriel'),
  ('André luiz Samaniego', '540', '1587', 'inadimplente', 'Gabriel'),
  ('MARCOS ANTONIO DA SILVA', '542', '4069', 'inadimplente', 'Gabriel'),
  ('jonas batista de sousa', '618', '9728', 'inadimplente', 'Gabriel'),
  ('jose antonio sá barreto conceição', '617', '6629', 'inadimplente', 'Gabriel'),
  ('Jefferson Sanches Matela', '618', '6748', 'inadimplente', 'Gabriel'),
  ('Marcia Aparecida Moraes Santos', '617', '6725', 'inadimplente', 'Gabriel'),
  ('Vinicius Passos da Silva', '617', '5657', 'inadimplente', 'Gabriel'),
  ('DIEGO APARECIDO MARTINS DOS SANTOS', '461', '7982', 'inadimplente', 'Gabriel'),
  ('MAURI LELIS QUEIROZ JUNIOR', '617', '4983', 'inadimplente', 'Gabriel'),
  ('LUCILENE SOARES E SILVA LELIS', '619', '8946', 'inadimplente', 'Gabriel'),
  ('RAPHAEL BARBOSA GOLD', '617', '7657', 'inadimplente', 'Gabriel'),
  ('ERIK DOS SANTOS LIMA', '618', '5050', 'inadimplente', 'Gabriel'),
  ('Almir da Silva', '617', '1099', 'inadimplente', 'Gabriel'),
  ('JAIR SOARES ADORNO', '461', '2809', 'inadimplente', 'Gabriel'),
  ('JAIR SOARES ADORNO', '461', '1102', 'inadimplente', 'Gabriel'),
  ('GABRIEL FARINAZZO GOMES DE OLIVEIRA', '706', '5704', 'inadimplente', 'Gabriel'),
  ('Daiane Dalila Mendonça Sales', '704', '2991', 'inadimplente', 'Gabriel'),
  ('ANDERSON CLAYTON DE PAULA', '619', '6280', 'inadimplente', 'Gabriel'),
  ('Tereza Cristina Marques de Brito', '704', '1885', 'inadimplente', 'Gabriel'),
  ('JAIR SOARES ADORNO', '461', '4012', 'inadimplente', 'Thamires'),
  ('MAXSUEL SANTOS DA SILVA', '704', '1008', 'inadimplente', 'Thamires'),
  ('Vicente Batista de Brito', '704', '898', 'inadimplente', 'Thamires'),
  ('GILMAR MIRANDA DE BITRO', '617', '2913', 'inadimplente', 'Thamires'),
  ('JOSE MATEUS DA SILVA', '617', '8392', 'inadimplente', 'Thamires'),
  ('kauã gomes de jesus', '617', '8714', 'inadimplente', 'Thamires'),
  ('Jadson Lima Evangelista', '617', '8817', 'inadimplente', 'Thamires'),
  ('wenderson da Silva Café', '529', '3181', 'inadimplente', 'Thamires'),
  ('JOSÉ RICARDO BARBOSA MEDEIROS', '617', '8889', 'inadimplente', 'Thamires'),
  ('CAMILA CRISTINA DE OLIVEIRA GOMES', '529', '370', 'inadimplente', 'Thamires'),
  ('EDUARDO FRANCISCO', '542', '4356', 'inadimplente', 'Thamires'),
  ('LUIS HENRIQUE MARTINS DOS REIS', '618', '2401', 'inadimplente', 'Thamires'),
  ('Gilberto Teodoro da Cunha', '617', '2428', 'inadimplente', 'Thamires'),
  ('Jorge Felipe Vieira lima', '535', '1209', 'inadimplente', 'Thamires'),
  ('WALLACE ALVES BARBOSA', '619', '5177', 'inadimplente', 'Thamires'),
  ('Valdelino ramos  santos', '618', '6884', 'inadimplente', 'Thamires'),
  ('Myqueias lopes Celestino', '618', '4955', 'inadimplente', 'Thamires'),
  ('kleber pinto ribeiro', '618', '3391', 'inadimplente', 'Thamires'),
  ('carlos eduardo santos', '540', '1386', 'inadimplente', 'Thamires'),
  ('raimundo nonato alves de sousa', '617', '8594', 'inadimplente', 'Thamires'),
  ('FABIO SANTOS SILVA', '618', '6893', 'inadimplente', 'Thamires'),
  ('JULIEZIO PEREIRA ALVES', '531', '725', 'inadimplente', 'Thamires'),
  ('maykon ulisses da silva', '540', '3108', 'inadimplente', 'Thamires'),
  ('IRINEU AQUILES FERREIRA GOMES', '617', '9079', 'inadimplente', 'Thamires'),
  ('ELIMAR GOMES DA SILVA', '617', '5860', 'inadimplente', 'Thamires'),
  ('José Amauri Alves da Silva', '618', '88', 'inadimplente', 'Thamires'),
  ('BIANCA FARINAZZO GOMES CHAGAS', '706', '5876', 'inadimplente', 'Thamires'),
  ('ARIELSON REIS DE SOUZA', '617', '9020', 'inadimplente', 'Thamires'),
  ('DEIVISON AUGUSTO DE SOUZA ALVES', '617', '124', 'inadimplente', 'Thamires'),
  ('CRISTIANO APARECIDO DOS SANTOS', '617', '8251', 'inadimplente', 'Thamires'),
  ('EDINILDO MAIA COSTA', '617', '8236', 'inadimplente', 'Thamires'),
  ('RYAN GOUDINHO MARQUES', '465', '227', 'inadimplente', 'Thamires'),
  ('FRANCISCO CANTARELE VICENTE', '617', '6199', 'inadimplente', 'Thamires'),
  ('Rômulo de Souza Navega da Silva', '617', '6992', 'inadimplente', 'Thamires'),
  ('BRENO RENATO ALVES CAMPOS', '616', '1243', 'inadimplente', 'Thamires'),
  ('JOSUE RIBEIRO DOS SANTOS FILHO', '540', '1210', 'inadimplente', 'Thamires'),
  ('Leandro José Alves', '617', '7453', 'inadimplente', 'Thamires'),
  ('SERGIO NOGUEIRA', '617', '8644', 'inadimplente', 'Thamires'),
  ('RENATO GANZERT', '616', '341', 'inadimplente', 'Thamires'),
  ('joao henrique soares gaioski', '616', '21', 'inadimplente', 'Thamires'),
  ('Felipe Silva Moura Brasil', '5000', '3890', 'inadimplente', 'Thamires'),
  ('Murilo Mozart de Souza Pereira', '535', '3448', 'inadimplente', 'Thamires'),
  ('LUCIANO DO NASCIMENTO GOMES', '542', '9202', 'inadimplente', 'Thamires'),
  ('RODRIGO APARECIDO  DE PONTES', '617', '8896', 'inadimplente', 'Thamires'),
  ('ICARO MATHEUS AMARO MONTEIRO', '617', '8218', 'inadimplente', 'Thamires'),
  ('JOÃO VICTOR DE OLIVEIRA SOUZA', '617', '5686', 'inadimplente', 'Thamires'),
  ('Cicero da silva lourenço', '617', '8650', 'inadimplente', 'Thamires'),
  ('JOSE ALCIRLEY DA SILVA', '538', '1054', 'inadimplente', 'Thamires'),
  ('jackson carlos lopes dos santos', '617', '5156', 'inadimplente', 'Thamires'),
  ('Francisley Gonçalves Ferreira', '618', '7350', 'inadimplente', 'Thamires'),
  ('LEONARDO RAFAEL BITTAR', '617', '268', 'inadimplente', 'Thamires'),
  ('EDINALDO CRUZ DA COSTA', '618', '935', 'cancelado', 'Thamires'),
  ('LEANDRO GABRIEL DA SILVA', '618', '3993', 'cancelado', 'Thamires'),
  ('CARLOS HENRIQUE FERNANDES COSTA', '618', '8176', 'cancelado', 'Cley'),
  ('MADMA DA SILVA OLIVEIRA', '618', '9180', 'cancelado', 'Cley'),
  ('HILDERLANIA RAIHALLA BUSATTA', '619', '5597', 'cancelado', 'Cley'),
  ('PAULO HENRIQUE ALVES CABRAL', '618', '7074', 'cancelado', 'Cley'),
  ('CÁSSIA SILVA MONTEIRO', '618', '7001', 'cancelado', 'Cley'),
  ('ELIVAR GONCALVES ALVES', '618', '3503', 'cancelado', 'Cley'),
  ('AMARILDO COSTA POLONINE JUNIOR', '618', '4958', 'cancelado', 'Cley'),
  ('SAULO DE CASSIO DA SILVA SANTOS', '616', '413', 'cancelado', 'Cley'),
  ('NADSON FRANCISCO MATOS OLIVEIRA', '618', '8147', 'cancelado', 'Cley'),
  ('CRISTIANO DA SILVA DE OLIVEIRA', '704', '1879', 'cancelado', 'Cley'),
  ('RICARDO CUNHA MENDES', '618', '7983', 'cancelado', 'Cley'),
  ('RIKELMY RODRIGUES CASTRO', '618', '2440', 'cancelado', 'Cley'),
  ('CX ASSET MANAGEMENT LTDA.', '618', '8577', 'cancelado', 'Cley'),
  ('JOSE FILHO PEREIRA BARROS', '618', '305', 'cancelado', 'Cley'),
  ('CLAUDIO SILVA PINHEIRO', '618', '4167', 'cancelado', 'Cley'),
  ('MANOEL JARDIM DE JESUS', '618', '1275', 'cancelado', 'Cley'),
  ('MARCELO ROBERTO PIRES', '618', '2811', 'cancelado', 'Cley'),
  ('EDUARDO BARROS RIBEIRO', '619', '422', 'cancelado', 'Cley'),
  ('HELEN VICTORIA DOS SANTOS DE ARAUJO', '706', '6521', 'cancelado', 'Cley'),
  ('RAFAEL SANTOS PEREIRA', '618', '3485', 'cancelado', 'Cley'),
  ('JAIR ANTUNES', '616', '900', 'cancelado', 'Cley'),
  ('JOAO BATISTA GARCIA JUNIOR', '618', '6298', 'cancelado', 'Cley'),
  ('IRIS GONÇALVES LIMA', '540', '628', 'cancelado', 'Cley'),
  ('IRIS GONÇALVES LIMA', '616', '500', 'cancelado', 'Cley'),
  ('DALMACIO DE SOUZA SANTOS', '618', '4218', 'cancelado', 'Cley'),
  ('FERNANDO BATISTA BARROS', '617', '1673', 'cancelado', 'Cley'),
  ('ISRAEL ALVES DA SILVA', '618', '9281', 'cancelado', 'Cley'),
  ('PABLO MARCELINO DE LIMA', '618', '8208', 'cancelado', 'Cley'),
  ('WAGNER DOS SANTOS PINTO', '463', '1523', 'cancelado', 'Cley'),
  ('SUENYA CRISTINA PEREIRA BARBOSA', '618', '8428', 'cancelado', 'Cley'),
  ('ANDRÉ CHINOTTI', '618', '747', 'cancelado', 'Cley'),
  ('MARCUS VINICIUS RODRIGUES DIAS', '618', '8991', 'cancelado', 'Cley'),
  ('LUCAS PIXITORI NOVELLI', '618', '7509', 'cancelado', 'Cley'),
  ('KAIQUE SILVA NOGUEIRA', '618', '2941', 'cancelado', 'Cley'),
  ('MARCO AURÉLIO ALVES NOGUEIRA', '463', '252', 'cancelado', 'Cley'),
  ('WILLIAM RODRIGUES DE CASTRO', '618', '4352', 'cancelado', 'Cley'),
  ('ALIANO ALVES PONTES DE ALMEIDA', '617', '196', 'cancelado', 'Cley'),
  ('WELLINGTON ELOY ALVES CORREA', '618', '4805', 'cancelado', 'Cley'),
  ('DAVID BATISTA SILVA', '617', '1134', 'cancelado', 'Cley'),
  ('GABRIEL DA CRUZ RIGO', '618', '4398', 'cancelado', 'Cley'),
  ('PEDRO LUCAS DO EGITO CASTRO', '618', '1118', 'cancelado', 'Cley'),
  ('GABRIEL JOAQUIM DA SILVA', '618', '2990', 'cancelado', 'Cley'),
  ('MARIA LUIZA BAGINI CHOPTIAN', '459', '181', 'cancelado', 'Cley'),
  ('EDSON MARCELO DA CUNHA', '617', '2210', 'cancelado', 'Cley'),
  ('CLAUDINEI DE MACEDO ALVES', '618', '8819', 'cancelado', 'Cley'),
  ('RICARDO ROCHA BORTOLOTTO', '618', '8471', 'cancelado', 'Cley'),
  ('DANIEL DE MORAES CARVALHO', '618', '5232', 'cancelado', 'Cley'),
  ('MIRIAN', '704', '1890', 'cancelado', 'Cley'),
  ('FABIANO CICERO DA SILVA', '540', '1328', 'cancelado', 'Cley'),
  ('EDSON LUSINDRO JUNIOR', '618', '964', 'cancelado', 'Cley'),
  ('CRISTIANO DE SOUZA', '704', '1564', 'cancelado', 'Cley'),
  ('CRISTIANO RAMOS DOS SANTOS', '704', '1482', 'cancelado', 'Cley'),
  ('ANTONIO MARCOS ALVES', '618', '4936', 'cancelado', 'Cley'),
  ('EURICO FRANCISCO BEZERRA NETO', '618', '7159', 'cancelado', 'Gabriel'),
  ('KLEBER MACIEL DE ARAUJO FILHO', '618', '1377', 'cancelado', 'Gabriel'),
  ('VINICIUS SIMIONATO', '540', '234', 'cancelado', 'Gabriel'),
  ('ISADORA CAROLINE PAULINO DOS SANTOS', '540', '1645', 'cancelado', 'Gabriel'),
  ('MARCO AURELIO DE PADUA', '616', '1363', 'cancelado', 'Gabriel'),
  ('CICERO CARDOSO DA SILVA', '704', '1438', 'cancelado', 'Gabriel'),
  ('ROBSON SANTOS DA SILVA', '618', '7828', 'cancelado', 'Gabriel'),
  ('PAULO HENRIQUE LACERDA LAGARES', '618', '8598', 'cancelado', 'Gabriel'),
  ('GLEISSON  JULIANO LEAO DE OLIVEIRA', '618', '7390', 'cancelado', 'Gabriel'),
  ('FRANCISCO AUGUSTO DE MEDEIROS SARAIVA', '538', '2505', 'cancelado', 'Gabriel'),
  ('ROGERIO AGOSTINHO DA SILVA', '618', '7053', 'cancelado', 'Gabriel'),
  ('MARIA LUIZA CELESTE NEVES', '618', '2558', 'cancelado', 'Gabriel'),
  ('EMANUEL HENRIQUE SOUSA', '540', '2080', 'cancelado', 'Gabriel'),
  ('ARTHUR AUGUSTO DE SOUZA', '618', '719', 'cancelado', 'Gabriel'),
  ('MARCOS RIBEIRO SOUTO', '618', '1190', 'cancelado', 'Gabriel'),
  ('EDSON SILVA LINS', '618', '6763', 'cancelado', 'Gabriel'),
  ('ROBSON DA SILVA LIMA', '618', '1374', 'cancelado', 'Gabriel'),
  ('CAMILA CRISTINA DE OLIVEIRA GOMES', '540', '2148', 'cancelado', 'Gabriel'),
  ('VAN HELSEN FERNANDES CARDOSO', '618', '4064', 'cancelado', 'Gabriel'),
  ('AGNALDO PEREIRA DE MORAES', '618', '9538', 'cancelado', 'Gabriel'),
  ('JOEL NUNES FERREIRA', '618', '5736', 'cancelado', 'Gabriel'),
  ('EDILSON VIANA DE BRITO', '618', '6488', 'cancelado', 'Gabriel'),
  ('ROSANDRO TUMBA LEMOS', '704', '1988', 'cancelado', 'Gabriel'),
  ('EDER CAMBRUZZI', '616', '697', 'cancelado', 'Gabriel'),
  ('CX ASSET MANAGEMENT LTDA.', '618', '9065', 'cancelado', 'Gabriel'),
  ('BRUNA GUIMARÃES RODRIGUES', '616', '971', 'cancelado', 'Gabriel'),
  ('MARIA ISABEL DE CARVALHO ROCHA', '540', '1727', 'cancelado', 'Gabriel'),
  ('SANDRO  MORAES DECOL', '618', '250', 'cancelado', 'Gabriel'),
  ('PHELIPE EMANOEL SOUZA SANTOS', '618', '9610', 'cancelado', 'Gabriel'),
  ('JHONATAN AURÉLIO DE MACEDO', '616', '207', 'cancelado', 'Gabriel'),
  ('IALESSON KELVIN SOARES DA SILVA', '618', '2201', 'cancelado', 'Gabriel'),
  ('JOHNATHANS MATHEUS DE SOUZA CAIRES MELO', '618', '4305', 'cancelado', 'Gabriel'),
  ('IRIS GONÇALVES LIMA', '462', '4192', 'cancelado', 'Gabriel'),
  ('KAIO CÉSAR SILVA VIEIRA', '618', '1447', 'cancelado', 'Gabriel'),
  ('THALES JOSE PEREIRA DA SILVA', '541', '941', 'cancelado', 'Gabriel'),
  ('PEDRO BEZERRA FURTADO', '541', '460', 'cancelado', 'Gabriel'),
  ('PEDRO BEZERRA FURTADO', '616', '1307', 'cancelado', 'Gabriel'),
  ('JULIANO DIAS DE OLIVEIRA', '5000', '6678', 'cancelado', 'Gabriel'),
  ('WELLINGTON RAFAEL ALVES DE ALENCAR', '618', '9224', 'cancelado', 'Gabriel'),
  ('RICARDO HENRIQUE CORREIA', '617', '1682', 'cancelado', 'Gabriel'),
  ('MARCOS GERSON DA COSTA', '617', '3477', 'cancelado', 'Gabriel'),
  ('MAICON DA SILVA PEREIRA', '706', '9724', 'cancelado', 'Gabriel'),
  ('IRINEU AQUILES FERREIRA GOMES', '617', '3438', 'cancelado', 'Gabriel'),
  ('JORGE ALVES PESSOA', '540', '2747', 'cancelado', 'Gabriel'),
  ('BRUNO PARRAS  DOMINGOS TONDATO', '618', '68', 'cancelado', 'Gabriel'),
  ('JOSE MANOEL DA SILVA PEREIRA', '616', '1079', 'cancelado', 'Gabriel'),
  ('ARQUIMEDES CARDOSO DE OLIVEIRA JUNIOR', '617', '3400', 'cancelado', 'Gabriel'),
  ('BRUNA HASSEN MELIGA', '616', '975', 'cancelado', 'Gabriel'),
  ('BIANCA FARINAZZO GOMES CHAGAS', '619', '9631', 'cancelado', 'Gabriel'),
  ('ADAM TENAN DE BARROS', '617', '3870', 'cancelado', 'Gabriel'),
  ('RENATO DO VALE', '461', '9528', 'cancelado', 'Gabriel'),
  ('LUCAS VIEIRA LEAL DE PAULA', '618', '9443', 'cancelado', 'Gabriel'),
  ('BRUNO CARLOS DE LIMA', '618', '8400', 'cancelado', 'Gabriel'),
  ('CARLOS JEAN DE SOUZA BARBOSA', '617', '2909', 'cancelado', 'Thamires'),
  ('MICKAEL ANTONIO DA SILVA GONÇALVES DE SOUZA', '541', '273', 'cancelado', 'Thamires'),
  ('HIGOR PHELIPE DE BARROS PEREIRA', '540', '2525', 'cancelado', 'Thamires'),
  ('HENRI PIRUTTI SALVADOR', '525', '760', 'cancelado', 'Thamires'),
  ('MARCOS DE JESUS PANCOLIN', '538', '5787', 'cancelado', 'Thamires'),
  ('BAUER GOUVEA DA SILVA', '618', '9928', 'cancelado', 'Thamires'),
  ('JOSE PEREIRA SOBRINHO', '617', '3947', 'cancelado', 'Thamires'),
  ('ARIELSON REIS DE SOUZA', '5000', '4412', 'cancelado', 'Thamires'),
  ('BIANCA FARINAZZO GOMES CHAGAS', '707', '1614', 'cancelado', 'Thamires'),
  ('JOSE MATEUS DA SILVA', '618', '8350', 'cancelado', 'Thamires'),
  ('JOSIAS CAMILO DA APRESENTAÇÃO FILHO', '618', '5037', 'cancelado', 'Thamires'),
  ('GUSTAVO ALVES DE PAULA', '618', '4657', 'cancelado', 'Thamires'),
  ('LUCAS DIAS DA SILVA', '704', '2453', 'cancelado', 'Thamires'),
  ('JONINSON OLIVEIRA SANTOS', '617', '150', 'cancelado', 'Thamires'),
  ('VINICIUS ARTHUR ENGRACIO BARBOSA', '618', '6617', 'cancelado', 'Thamires'),
  ('RAÍ GONÇALVES LEMOS', '704', '2568', 'cancelado', 'Thamires'),
  ('MILVA MOURA DA ROSA JURADO', '539', '9518', 'cancelado', 'Thamires'),
  ('DAYANY FERNANDES DE MELLO SILVA TEIXEIRA', '463', '2300', 'cancelado', 'Thamires'),
  ('DOUGLAS GODINHO DE PAULA VIEIRA', '618', '3364', 'cancelado', 'Thamires'),
  ('FABÍOLA ALVES LEAL', '538', '149', 'cancelado', 'Thamires'),
  ('MIGUEL ALVES SILVA', '617', '4813', 'cancelado', 'Thamires'),
  ('NICKOLAS PEDRO DA SILVA PASSOS', '617', '4693', 'cancelado', 'Thamires'),
  ('FELIPE MATHEUS GOMES SILVA', '618', '4555', 'cancelado', 'Thamires'),
  ('JOSE CARLOS COELHO', '618', '1201', 'cancelado', 'Thamires'),
  ('FRANCISCO MATOS DA SILVA', '618', '6477', 'cancelado', 'Thamires'),
  ('GABRIEL TEIXEIRA CARDOSO', '618', '5705', 'cancelado', 'Thamires'),
  ('ALEC VICTOR DE SOUZA', '617', '4002', 'cancelado', 'Thamires'),
  ('LENILSON REBOUÇAS DIAS', '618', '1712', 'cancelado', 'Thamires'),
  ('VALMIR VITT', '617', '2331', 'cancelado', 'Thamires'),
  ('MARCOS RIBEIRO SOUTO', '704', '608', 'cancelado', 'Thamires'),
  ('TASSIO VIEIRA DOURADO', '617', '284', 'cancelado', 'Thamires'),
  ('MATEUS FERREIRA RIBEIRO', '618', '4494', 'cancelado', 'Thamires'),
  ('JOSÉ LEARTE DE PAULA', '617', '4834', 'cancelado', 'Thamires'),
  ('WERNER BAIA DOS SANTOS', '617', '3563', 'cancelado', 'Thamires'),
  ('DANILO APARECIDO BENDER', '5000', '7411', 'cancelado', 'Thamires'),
  ('MATHEUS SANTOS FERREIRA', '618', '4111', 'cancelado', 'Thamires'),
  ('RAFAEL VITOR DE MIRANDA MEDEIROS', '617', '4051', 'cancelado', 'Thamires'),
  ('VITOR SANTANA ALVES', '617', '4312', 'cancelado', 'Thamires'),
  ('ANDERSON SANTOS MOURA', '618', '8960', 'cancelado', 'Thamires'),
  ('MANOEL LUIZ DOS SANTOS', '540', '3899', 'cancelado', 'Thamires'),
  ('WILIAN WAINAROSKI', '539', '2831', 'cancelado', 'Thamires'),
  ('IGOR FRANCISCO FERREIRA', '539', '9648', 'cancelado', 'Thamires'),
  ('CARLOS VINICIUS DOS SANTOS CARDOSO', '539', '7984', 'cancelado', 'Thamires'),
  ('WILLIAN DONIZETE DOS SANTOS', '539', '2828', 'cancelado', 'Thamires'),
  ('CAUÃ ALEXANDRE FERREIRA DA SILVA', '618', '3007', 'cancelado', 'Thamires'),
  ('THEL DA SILVA SANTOS', '618', '3677', 'cancelado', 'Thamires'),
  ('LEANDRO MARTINS FERREIRA RODRIGUES', '618', '3574', 'cancelado', 'Thamires'),
  ('MAXWELL PEREIRA DA SILVA', '618', '9692', 'cancelado', 'Thamires'),
  ('MARCOS ANTONIO DA SILVA', '540', '846', 'cancelado', 'Thamires'),
  ('ROBERTO FERREIRA DE SOUSA', '540', '3565', 'cancelado', 'Thamires'),
  ('NICOLAS CRISTIANO TAVARES SOTERIO', '618', '4628', 'cancelado', 'Thamires'),
  ('DAVID LEONEL MUNIZ', '618', '6504', 'cancelado', 'Thamires'),
  ('DIEGO DE SOUZA MACHADO', '538', '966', 'cancelado', 'Thamires'),
  ('ANDREY BATISTA ALVES', '539', '8393', 'cancelado', 'Cley'),
  ('PABLO HENRIQUE CAMARGO BRANCO', '618', '544', 'cancelado', 'Cley'),
  ('JESSICA SILVA LOPES DOS SANTOS', '618', '847', 'cancelado', 'Cley'),
  ('CARLOS HENRIQUE JUSTOS', '617', '5638', 'cancelado', 'Cley'),
  ('EDNA ALVES DOS SANTOS', '706', '1372', 'cancelado', 'Cley'),
  ('WELLYNGTON ALVES RODRIGUES', '618', '2799', 'cancelado', 'Cley'),
  ('PEDRO GABRIEL AICHINO SILVA', '617', '2842', 'cancelado', 'Cley'),
  ('HUDSON DA ROCHA ALBUQUERQUE', '704', '386', 'cancelado', 'Cley'),
  ('MATHEUS OLIVEIRA SANTANA', '539', '332', 'cancelado', 'Cley'),
  ('TULIO COSTA SILVA', '618', '3111', 'cancelado', 'Cley'),
  ('ITALO SANTOS FERREIRA', '617', '4947', 'cancelado', 'Cley'),
  ('CARLOS HENRIQUE GONCALVES RANGEL DE SOUZA', '462', '2763', 'cancelado', 'Cley'),
  ('DIEGO MARANHÃO DA SILVA', '617', '3747', 'cancelado', 'Cley'),
  ('CAIO FERNANDES RIBEIRO', '540', '3596', 'cancelado', 'Cley'),
  ('ANTONIO RODOLFO VENANCIO BERNARDO', '618', '3078', 'cancelado', 'Cley'),
  ('IGOR TARCIANO DA SILVA COUTINHO', '617', '5979', 'cancelado', 'Cley'),
  ('SANDRA DE OLIVEIRA LIMA ALENCAR', '540', '536', 'cancelado', 'Cley'),
  ('WILSON DA SILVA RODRIGUES JUNIOR', '539', '6766', 'cancelado', 'Cley'),
  ('DANIEL SILVA CONCEIÇÃO', '616', '692', 'cancelado', 'Cley'),
  ('WESLEY APARECIDO JULIANI', '617', '4382', 'cancelado', 'Cley'),
  ('EDUARDO JOEL JESUZ NASCIMENTO DA SILVA', '617', '5194', 'cancelado', 'Cley'),
  ('ADREAN HENRIQUE DA SILVA LIMA', '618', '1257', 'cancelado', 'Cley'),
  ('LUCAS ROSA DA SILVA', '618', '6763', 'cancelado', 'Cley'),
  ('LEONARDO BARBOSA MENDES', '539', '1536', 'cancelado', 'Cley'),
  ('MATHEUS NASCIMENTO ALEXANDRE', '617', '3034', 'cancelado', 'Cley'),
  ('FRANCISCO AUGUSTO DE MEDEIROS SARAIVA', '617', '288', 'cancelado', 'Cley'),
  ('GABRIEL HENRIQUE GUIMARAES DE SOUZA', '618', '9237', 'cancelado', 'Cley'),
  ('LEONIDAS DO CARMO REIS', '618', '5963', 'cancelado', 'Cley'),
  ('DOUGLAS FERNANDO P. DO NASCIMENTO', '616', '1211', 'cancelado', 'Cley'),
  ('WILSON SOUZA SILVA', '617', '4299', 'cancelado', 'Cley'),
  ('JOÃO PAULO DA SILVA THEODORO', '706', '8580', 'cancelado', 'Cley'),
  ('MARCELO MARQUES TORET', '617', '795', 'cancelado', 'Cley'),
  ('VINICIUS ALVES DA SILVA', '618', '9800', 'cancelado', 'Cley'),
  ('TASSIO VIEIRA DOURADO', '706', '961', 'cancelado', 'Cley'),
  ('ESTHEFHANNY THALYA DOS SANTOS', '540', '2540', 'cancelado', 'Cley'),
  ('EVA MARIA DA SILVA', '618', '9576', 'cancelado', 'Cley'),
  ('ANTONIO MENDES DA SILVA FILHO', '539', '2235', 'cancelado', 'Cley'),
  ('ERLANDSSON CARVALHO DO NASCIMENTO MOURA', '617', '1077', 'cancelado', 'Cley'),
  ('ANDERSON DOS SANTOS SILVA', '463', '4412', 'cancelado', 'Cley'),
  ('LENILDO RODRIGUES DE OLIVEIRA', '616', '1242', 'cancelado', 'Cley'),
  ('FERNANDO RODRIGUES DA SILVA', '616', '207', 'cancelado', 'Cley'),
  ('MICHAEL DEMETRIOS TEIXEIRA MESQUITA', '619', '5195', 'cancelado', 'Cley'),
  ('NATALIA RODRIGUES NEVES', '529', '2779', 'cancelado', 'Cley'),
  ('MAIKEL WILIAN ARCANJO DE JESUS', '617', '6029', 'cancelado', 'Cley'),
  ('EUDA MACIEL BENTO', '618', '6338', 'cancelado', 'Cley'),
  ('ELIEZER SANTOS DE JESUS', '617', '6823', 'cancelado', 'Cley'),
  ('PAULO JOSE SILVA MARQUES', '618', '5628', 'cancelado', 'Cley'),
  ('GUSTAVO TAKASHI BARBOSA COSTA', '541', '490', 'cancelado', 'Cley'),
  ('MAYLTON DOUGLAS DA SILVA', '617', '6519', 'cancelado', 'Cley'),
  ('ANDRE LUIZ NOGUEIRA ROSA', '618', '9164', 'cancelado', 'Cley'),
  ('JOAO LUIS GAMBINI DA SILVA', '618', '1945', 'cancelado', 'Cley'),
  ('FERNANDO LUIS BARRETOS SANTOS', '618', '7164', 'cancelado', 'Cley'),
  ('CRISOSTOMO ANTÔNIO DE SOUSA', '618', '8036', 'cancelado', 'Cley'),
  ('JOAO LUIS GAMBINI DA SILVA', '618', '7016', 'cancelado', 'Gabriel'),
  ('EDUARDO DE OLIVEIRA CARDOSO', '618', '9824', 'cancelado', 'Gabriel'),
  ('ALISON FILGUEIRA MORAES', '617', '6161', 'cancelado', 'Gabriel'),
  ('ALAILSON DA SILVA', '618', '9146', 'cancelado', 'Gabriel'),
  ('THIAGO EMILIO PIMENTEL BARROS', '618', '5091', 'cancelado', 'Gabriel'),
  ('BRUNO GARCIA TATAGIBA MEDINA', '618', '9041', 'cancelado', 'Gabriel'),
  ('DANILO APARECIDO BENDER', '5000', '1673', 'cancelado', 'Gabriel'),
  ('KAIKE FERREIRA SILVA', '618', '2031', 'cancelado', 'Gabriel'),
  ('RAFAEL MIRANDA DE MELO', '618', '6967', 'cancelado', 'Gabriel'),
  ('ELISANGELA SILVA GASPERAZZO', '618', '1018', 'cancelado', 'Gabriel'),
  ('KAUÃ DA SILVA AGUIAR', '617', '7374', 'cancelado', 'Gabriel'),
  ('LUIZ AUGUSTO ALVES DI PASSOS', '617', '2889', 'cancelado', 'Gabriel'),
  ('EVANILSON CRUZ DOS SANTOS', '540', '708', 'cancelado', 'Gabriel'),
  ('ROBSON MIGUEL DOS SANTOS', '617', '7615', 'cancelado', 'Gabriel'),
  ('PAULO HENRIQUE JORDÃO', '617', '4393', 'cancelado', 'Gabriel'),
  ('EVANDRO CLARO DE MATOS', '617', '7325', 'cancelado', 'Gabriel'),
  ('GABRIEL CAVALCANTE MEDEIROS DA CRUZ', '617', '7814', 'cancelado', 'Gabriel'),
  ('RICHARD NUNES DE PAULA CARDOSO', '617', '8028', 'cancelado', 'Gabriel'),
  ('MAÍRA GABRIELE OLIVEIRA DA SILVA', '618', '9591', 'cancelado', 'Gabriel'),
  ('LUCIANO DOS SANTOS FERREIRA', '540', '3736', 'cancelado', 'Gabriel'),
  ('EVANDRO BERNALDO DA SILVA', '618', '8242', 'cancelado', 'Gabriel'),
  ('Isaque Santos Lima', '539', '5358', 'cancelado', 'Gabriel'),
  ('ELIMAR GOMES DA SILVA', '617', '7458', 'cancelado', 'Gabriel'),
  ('Gustavo Alves Mascarenhas', '617', '1134', 'cancelado', 'Gabriel'),
  ('GUILHERME STEIN MUNDINS', '535', '980', 'cancelado', 'Gabriel'),
  ('REGINALDO MONTEIRO DOS SANTOS', '617', '2757', 'cancelado', 'Gabriel'),
  ('henrique matias bezerra', '617', '7470', 'cancelado', 'Gabriel'),
  ('CARLOS ALBERTO MOREIRA DOS SANTOS', '5000', '295', 'cancelado', 'Gabriel'),
  ('GUILHERME AUGUSTO GEWE SOUSA', '618', '9805', 'cancelado', 'Gabriel'),
  ('CARLOS ALBERTO MOREIRA DOS SANTOS', '618', '2972', 'cancelado', 'Gabriel'),
  ('caio victor ribeiro da cunha', '617', '7660', 'cancelado', 'Gabriel'),
  ('JUNIOR VARGAS DA SILVA', '617', '4391', 'cancelado', 'Gabriel'),
  ('Bruno Ramos da Silva', '618', '5072', 'cancelado', 'Gabriel'),
  ('DIEGO MOREIRA DE CARVALHO', '5000', '808', 'cancelado', 'Gabriel'),
  ('KELMY YULMI HINATA', '704', '356', 'cancelado', 'Gabriel'),
  ('KELMY YULMI HINATA', '704', '359', 'cancelado', 'Gabriel'),
  ('MARCELO TOMAS OLIVEIRA DOS SANTOS', '618', '576', 'cancelado', 'Gabriel'),
  ('Kauan Vieira de Andrade', '617', '5105', 'cancelado', 'Gabriel'),
  ('marcone gomes da silva', '618', '3157', 'cancelado', 'Gabriel'),
  ('DEYVYDY ROBERTO SILVA DE OLIVEIRA', '618', '3694', 'cancelado', 'Gabriel'),
  ('gilvan da costa delgado', '618', '2359', 'cancelado', 'Gabriel'),
  ('PEDRO MIGUEL DIAS LEITE', '525', '561', 'cancelado', 'Gabriel'),
  ('JOSE NILTON DA SILVA', '542', '9391', 'cancelado', 'Gabriel'),
  ('Junior Carlos Silva', '618', '2658', 'cancelado', 'Gabriel'),
  ('CARLOS DANIEL BATISTA SILVANO', '618', '9589', 'cancelado', 'Gabriel'),
  ('Gustavo Eugênio Ferreira', '617', '4907', 'cancelado', 'Gabriel'),
  ('Thiago James Oliveira Lima', '617', '407', 'cancelado', 'Gabriel'),
  ('VINICIUS ALVES DA SILVA', '617', '2347', 'cancelado', 'Gabriel'),
  ('Mateus de Carvalho Ribeiro', '618', '3781', 'cancelado', 'Gabriel'),
  ('Abner Pierre Reis', '617', '5081', 'cancelado', 'Gabriel'),
  ('Ygor Gabriel Silva Rodrigues', '617', '2357', 'cancelado', 'Gabriel'),
  ('Isabella Meneses de Queiroz Marques Vilar', '618', '8286', 'cancelado', 'Gabriel'),
  ('PATRÍCIA KELLEN VIEIRA', '618', '9069', 'cancelado', 'Gabriel'),
  ('JULIO ANDRE GUEDES DOS SANTOS', '617', '6383', 'cancelado', 'Thamires'),
  ('Emanuel Soares Durans', '617', '7758', 'cancelado', 'Thamires'),
  ('rafael peruche rodine', '618', '904', 'cancelado', 'Thamires'),
  ('Pedro Lucas Bahia de Souza', '618', '8444', 'cancelado', 'Thamires'),
  ('CLARIVAL DO ESPÍRITO SANTOS', '618', '8349', 'cancelado', 'Thamires'),
  ('AURÉLIO MOISES NUNES FREIRE FILHO', '618', '6383', 'cancelado', 'Thamires'),
  ('MAYELY DOS SANTOS SILVA', '617', '8895', 'cancelado', 'Thamires'),
  ('LORENA TEIXEIRA BESERRA', '618', '2708', 'cancelado', 'Thamires'),
  ('YURI HENRIQUE DA SILVA PONTES', '618', '8461', 'cancelado', 'Thamires'),
  ('Arsênio Clarindo Ferreira Filho', '460', '523', 'cancelado', 'Thamires'),
  ('IKARO FABRICIO CARCERES DA SILVA', '529', '8751', 'cancelado', 'Thamires'),
  ('Alvaro Crivellari Garcia', '535', '1078', 'cancelado', 'Thamires'),
  ('JOHN WILLIANS FERREIRA CALDAS', '533', '451', 'cancelado', 'Thamires'),
  ('Rusembergue Dias de Oliveira', '533', '612', 'cancelado', 'Thamires'),
  ('Rejane Maria da Silva Torres', '616', '70', 'cancelado', 'Thamires'),
  ('Leonardo Mendonça lima', '617', '7655', 'cancelado', 'Thamires'),
  ('ROBSON DE SOUZA CARDOZO DA SILVA', '616', '1010', 'em_dia', 'Thamires'),
  ('RUAN ARAUJO ARMANDO', '618', '8540', 'em_dia', 'Thamires'),
  ('MARCONIESON SPADINI BARBOSA', '618', '2292', 'em_dia', 'Thamires'),
  ('EDMILSON JOSE DE SOUZA', '618', '6416', 'em_dia', 'Thamires'),
  ('FABIO DO ESPIRITO SANTO', '618', '8586', 'em_dia', 'Thamires'),
  ('THIAGO DIAS RANGEL', '616', '200', 'em_dia', 'Thamires'),
  ('PAULO NEWTON GUEDES ALMEIDA', '618', '1055', 'em_dia', 'Thamires'),
  ('ARTUR FRANCISCO NUNES NETO', '617', '1465', 'em_dia', 'Thamires'),
  ('LINDOLFO CARNEIRO DA SILVA', '618', '960', 'em_dia', 'Thamires'),
  ('ALEX SILVA MOTA', '618', '2843', 'em_dia', 'Thamires'),
  ('JOSE LEONARDO DA SILVA FILHO', '618', '8881', 'em_dia', 'Thamires'),
  ('RUBEN MARQUES EUGÊNIO', '618', '5475', 'em_dia', 'Thamires'),
  ('MÁRCIO JEAN DOS SANTOS BATISTA', '618', '6533', 'em_dia', 'Thamires'),
  ('JOSE FERNANDES DOS SANTOS', '618', '6135', 'em_dia', 'Thamires'),
  ('DANIEL PERON GALDINO DE CARVALHO', '616', '707', 'em_dia', 'Thamires'),
  ('JOSE ILTON PEREIRA DE LIMA', '538', '8552', 'em_dia', 'Thamires'),
  ('LUCAS DELLA MURA D'' OLIVO', '618', '4391', 'em_dia', 'Thamires'),
  ('ROBERTO CARLOS MARTINS DOS SANTOS', '617', '879', 'em_dia', 'Thamires'),
  ('MARCOS DOS SANTOS DE OLIVEIRA', '618', '4381', 'em_dia', 'Thamires'),
  ('DAVID ANTÔNIO DA SILVA', '618', '9516', 'em_dia', 'Thamires'),
  ('GUILHERME ANDRADE DOS SANTOS', '618', '9383', 'em_dia', 'Thamires'),
  ('RAFAEL ARAÚJO DA SILVA', '617', '2383', 'em_dia', 'Thamires'),
  ('MARILSON RODRIGUES PINHEIRO', '618', '1480', 'em_dia', 'Thamires'),
  ('PROSPERINO VAZ VIEIRA SOBRINHO', '617', '1759', 'em_dia', 'Thamires'),
  ('ERICK THIAGO SOUZA DE OLIVEIRA', '617', '1985', 'em_dia', 'Thamires'),
  ('JAIR VICENTINI JUNIOR', '618', '4087', 'em_dia', 'Thamires'),
  ('LAVOARZIER  RIBEIRO DE OLIVEIRA', '704', '354', 'em_dia', 'Thamires'),
  ('ELIETE LADEIA SANTANA', '704', '1274', 'em_dia', 'Thamires'),
  ('ADRIANO BARBOZA DE AZEVEDO', '618', '7072', 'em_dia', 'Thamires'),
  ('MAURÍCIO MARINHO', '704', '1442', 'em_dia', 'Thamires'),
  ('JUCIMAR FERNANDES OLIVEIRA', '704', '615', 'em_dia', 'Thamires'),
  ('JOCIMAR COSTA DA CONCEICAO', '704', '176', 'em_dia', 'Thamires'),
  ('ANDRE DIEGO DOS SANTOS SOUZA', '541', '919', 'em_dia', 'Thamires'),
  ('JUNIO CESAR EVANGELISTA', '618', '8083', 'em_dia', 'Thamires'),
  ('SILVIO CRISTIANO SOUZA DE MENDES', '618', '3949', 'em_dia', 'Thamires'),
  ('KLERISSON DA SILVA MAMEDIO', '618', '6118', 'em_dia', 'Thamires'),
  ('THAMIRES MOTA DE SOUZA', '617', '989', 'em_dia', 'Thamires'),
  ('LEANDRO GOMES ALVES', '618', '3555', 'em_dia', 'Cley'),
  ('MARCELO CAMPOS MACHADO', '618', '8870', 'em_dia', 'Cley'),
  ('LUCAS DE SOUZA RIBEIRO SOARES', '617', '2091', 'em_dia', 'Cley'),
  ('CRISTIANO RODRIGUES LIMA', '618', '9328', 'em_dia', 'Cley'),
  ('WAGNER DE CARVALHO SANTOS', '616', '719', 'em_dia', 'Cley'),
  ('PATRICK LOPES PEREIRA', '618', '8097', 'em_dia', 'Cley'),
  ('CAIQUE LUIS RISSA SAHION', '616', '969', 'em_dia', 'Cley'),
  ('ISRAEL SILVA OLIVEIRA', '618', '7877', 'em_dia', 'Cley'),
  ('LEONAN FARIAS BRAZ RIBEIRO', '616', '431', 'em_dia', 'Cley'),
  ('RAFAEL APARECIDO SOARES NOBRE', '617', '3219', 'em_dia', 'Cley'),
  ('GIOVANE DIAS MANOEL', '617', '3211', 'em_dia', 'Cley'),
  ('ALIPIO NOVAES LIMA JUNIOR', '618', '7768', 'em_dia', 'Cley'),
  ('JULIANO DIAS DE OLIVEIRA', '618', '3402', 'em_dia', 'Cley'),
  ('JUVALCIR VIEIRA DA SILVA', '5000', '4070', 'em_dia', 'Cley'),
  ('ALIPIO NOVAES LIMA JUNIOR', '617', '3620', 'em_dia', 'Cley'),
  ('FELIPE JOSE VIEIRA', '618', '2434', 'em_dia', 'Cley'),
  ('MARCIA CAITANO LIMA DA SILVA', '617', '3264', 'em_dia', 'Cley'),
  ('DANILO DE SOUZA FERRARI', '706', '9525', 'em_dia', 'Cley'),
  ('CICERO DA CONCEIÇÃO DE MORAIS', '617', '3661', 'em_dia', 'Cley'),
  ('ALAN TORRES DE SOUZA', '618', '6353', 'em_dia', 'Cley'),
  ('LAERT CLEBSON MACHADO DE BARROS BATISTA SILVA DO NASCIMENTO', '616', '1273', 'em_dia', 'Cley'),
  ('THIAGO ARAUJO GALINDO', '618', '7240', 'em_dia', 'Cley'),
  ('RICARDO DANTAS DE OLIVEIRA', '618', '3209', 'em_dia', 'Cley'),
  ('ALENO SANDRO CAVALCANTE DA SILVA', '618', '3335', 'em_dia', 'Cley'),
  ('MARCO ANTONIO VAZ DE OLIVEIRA', '617', '3630', 'em_dia', 'Cley'),
  ('EDIMILSON ALBERIGI', '618', '1646', 'em_dia', 'Cley'),
  ('FRANCINEI DA SILVA NASCIMENTO', '531', '1259', 'em_dia', 'Cley'),
  ('CAROLINA DE MOURA LOURO', '616', '1219', 'em_dia', 'Cley'),
  ('ALESSANDRO NEVES DA SILVA', '617', '3285', 'em_dia', 'Cley'),
  ('NILTON CESAR MATOS SILVA', '538', '6023', 'em_dia', 'Cley'),
  ('FELIPE MATHEUS CAMPOS SANTANA DOS SANTOS', '618', '751', 'em_dia', 'Cley'),
  ('JOAO AUGUSTO SILVA DE OLIVEIRA', '618', '6768', 'em_dia', 'Cley'),
  ('MARCIO CESAR ROCHA', '618', '2027', 'em_dia', 'Cley'),
  ('WILLIAM DOS SANTOS LEMOS', '529', '718', 'em_dia', 'Cley'),
  ('KESLEY WILSON DE SOUSA', '618', '8867', 'em_dia', 'Cley'),
  ('LUISMAR SEBASIAO DUARTE', '617', '4247', 'em_dia', 'Cley'),
  ('DAVID PALMARES DA ROCHA GOMES', '618', '4172', 'em_dia', 'Cley'),
  ('GUILHERME DE OLIVEIRA DE  ARAUJO', '617', '4934', 'em_dia', 'Cley'),
  ('RUAN PABLO DA SILVA MELO', '540', '3147', 'em_dia', 'Cley'),
  ('SUELI DE LIMA ROCHA NASCIMENTO', '617', '4726', 'em_dia', 'Cley'),
  ('WILLIAN ROCHA LIMA DE MELO', '533', '564', 'em_dia', 'Cley'),
  ('RENATO MAGANHA MARQUES', '539', '3074', 'em_dia', 'Cley'),
  ('JOSE CARLOS LOLI JUNIOR', '618', '9806', 'em_dia', 'Cley'),
  ('HERALDO CANDIDO BENGNAMI', '617', '4819', 'em_dia', 'Cley'),
  ('SEBASTIÃO MATHEUS RIBEIRO DE ARAUJO', '618', '1730', 'em_dia', 'Cley'),
  ('EMERSON DA SILVA MENDES MACIEL', '540', '1830', 'em_dia', 'Cley'),
  ('ROGÉRIO FERNANDES DE SOUZA', '618', '4538', 'em_dia', 'Cley'),
  ('DANILO PEREIRA DA SILVA RODRIGUES', '618', '5874', 'em_dia', 'Cley'),
  ('RODRIGO ANTICO PIVA DA SILVA', '618', '8160', 'em_dia', 'Cley'),
  ('BOAZ DOS SANTOS SUEIRA', '618', '9195', 'em_dia', 'Cley'),
  ('JERFFERSON PLINIO ARAUJO DOS SANTOS', '617', '3179', 'em_dia', 'Cley'),
  ('MURILO ROBERTO MONZANI', '617', '4624', 'em_dia', 'Cley'),
  ('CELSO GALAMBA', '618', '3798', 'em_dia', 'Cley'),
  ('ELIAS DE CARVALHO GIMENES', '617', '4622', 'em_dia', 'Gabriel'),
  ('CLAUDIVAN APARECIDO  NICOLAU', '5000', '9134', 'em_dia', 'Gabriel'),
  ('CLAUDIVAN APARECIDO  NICOLAU', '617', '1965', 'em_dia', 'Gabriel'),
  ('SILVIO LUIZ SANTOS DE SANTANA', '617', '5804', 'em_dia', 'Gabriel'),
  ('ANA MARIA DALBEM PICORELLI', '617', '5402', 'em_dia', 'Gabriel'),
  ('EDER CARVALHO SANTOS', '618', '6605', 'em_dia', 'Gabriel'),
  ('DIONISIO ALMEIDA DAS NEVES.', '617', '5901', 'em_dia', 'Gabriel'),
  ('NILTON PEREIRA DE QUEIROGA', '531', '458', 'em_dia', 'Gabriel'),
  ('JOÃO PAULO DA SILVA THEODORO', '706', '8559', 'em_dia', 'Gabriel'),
  ('CARLOS HENRIQUE GONÇALVES MAIA', '535', '2722', 'em_dia', 'Gabriel'),
  ('VANESSA FERREIRA SILVA PORTO', '540', '393', 'em_dia', 'Gabriel'),
  ('ROGERIO ANTONIO AMADEU', '529', '4338', 'em_dia', 'Gabriel'),
  ('WAGNER LEAL DA PAIXÃO', '5000', '6487', 'em_dia', 'Gabriel'),
  ('ELY BETECEL DA COSTA', '541', '391', 'em_dia', 'Gabriel'),
  ('JOSIMAR SOBIS', '538', '965', 'em_dia', 'Gabriel'),
  ('ALEX OLIVEIRA REIS', '619', '8308', 'em_dia', 'Gabriel'),
  ('ADRIANO MORAES DE OLIVEIRA', '617', '5545', 'em_dia', 'Gabriel'),
  ('WEVERTON CLAUDINO DE CAMPOS', '617', '5268', 'em_dia', 'Gabriel'),
  ('VALQUIRIA LETICIA LIMA MELO', '617', '1372', 'em_dia', 'Gabriel'),
  ('RODRIGO LUIZ BATISTA DE OLIVEIRA', '616', '49', 'em_dia', 'Gabriel'),
  ('LEONARDO ÁLVARES PEIXOTO', '618', '4648', 'em_dia', 'Gabriel'),
  ('BRUNO RAPHAEL DE SOUZA NANTES', '618', '928', 'em_dia', 'Gabriel'),
  ('JONAS PEREIRA DA SILVA', '618', '7453', 'em_dia', 'Gabriel'),
  ('MARCOS ANTONIO DA SILVA', '617', '2406', 'em_dia', 'Gabriel'),
  ('FERNANDO CUNHA DE OLIVEIRA', '617', '5754', 'em_dia', 'Gabriel'),
  ('FRANCISCO LEONARDO DE MENEZES SEVERIANO', '617', '5369', 'em_dia', 'Gabriel'),
  ('FRANCISCO DAS CHAGAS OLIVEIRA DE AGUIAR', '616', '1431', 'em_dia', 'Gabriel'),
  ('CELSO APARECIDO DOS REIS', '529', '8156', 'em_dia', 'Gabriel'),
  ('JOSE RIBAMAR SERVILHO SILVA', '617', '5591', 'em_dia', 'Gabriel'),
  ('GILVANI GOMES DA COSTA', '616', '71', 'em_dia', 'Gabriel'),
  ('DAVIS FERNANDO GONÇALVES', '617', '5908', 'em_dia', 'Gabriel'),
  ('JOSE NILTON DA SILVA', '618', '3602', 'em_dia', 'Gabriel'),
  ('ANDERSON  DA CRUZ PINHEIRO', '617', '4676', 'em_dia', 'Gabriel'),
  ('RENATO CANDIDO DA SILVA', '617', '6354', 'em_dia', 'Gabriel'),
  ('ALEX DOS SANTOS', '617', '6534', 'em_dia', 'Gabriel'),
  ('ANTONIO MARCIO DA SILVA', '529', '8345', 'em_dia', 'Gabriel'),
  ('DAIANE ALVES MENDES', '618', '2586', 'em_dia', 'Gabriel'),
  ('SERGIO RICARDO DA SILVA', '618', '4749', 'em_dia', 'Gabriel'),
  ('CARLOS JOSE DE OLIVEIRA TOMAZ', '618', '2940', 'em_dia', 'Gabriel'),
  ('EDUARDO EUSTÁQUIO DOS SANTOS', '617', '7740', 'em_dia', 'Gabriel'),
  ('RENATO SILVESTRE', '618', '5550', 'em_dia', 'Gabriel'),
  ('DENILSON MOURA SOUSA SILVA', '618', '4970', 'em_dia', 'Gabriel'),
  ('PAULO CESAR GUIMARAES FILHO', '617', '4615', 'em_dia', 'Gabriel'),
  ('DAVID SANTOS SIQUEIRA', '539', '1692', 'em_dia', 'Gabriel'),
  ('LUCAS GABRIEL COUTINHO GERFE', '618', '5111', 'em_dia', 'Gabriel'),
  ('CLAUDIVAN APARECIDO  NICOLAU', '617', '6120', 'em_dia', 'Gabriel'),
  ('JAILTON CUSTODIO PEIXOTO', '5000', '6365', 'em_dia', 'Gabriel'),
  ('ANDRE JOSE TIAGO VIEIRA DE OLIVEIRA', '617', '3833', 'em_dia', 'Gabriel'),
  ('HENRIQUE YUKIO PEDROSO', '618', '6989', 'em_dia', 'Gabriel'),
  ('CÍCERO BORGES VIEIRA', '617', '7743', 'em_dia', 'Gabriel'),
  ('MACHAEL DOUGLAS SANTOS PIRES DA SILVA', '618', '8275', 'em_dia', 'Gabriel'),
  ('MARCIO ANTONIO SOARES CORREIA', '541', '408', 'em_dia', 'Gabriel'),
  ('ANTONIO CLAUDIO RIBEIRO DA SILVA', '617', '8033', 'em_dia', 'Gabriel'),
  ('RICARDO DOMINGUES DOS SANTOS', '5000', '9354', 'em_dia', 'Thamires'),
  ('EDUARDO SILVA GOMES', '617', '5391', 'em_dia', 'Thamires'),
  ('DAVI MARCOS FERREIRA', '617', '5662', 'em_dia', 'Thamires'),
  ('DANIEL APARECIDO DOS SANTOS', '5000', '9381', 'em_dia', 'Thamires'),
  ('VAN HELSEN FERNANDES CARDOSO', '617', '8003', 'em_dia', 'Thamires'),
  ('Anderson Siqueira Alves', '617', '7270', 'em_dia', 'Thamires'),
  ('ODAIR JOSE PEREIRA', '617', '8177', 'em_dia', 'Thamires'),
  ('JÚLIO CESAR FELIX DA SILVA', '5000', '4185', 'em_dia', 'Thamires'),
  ('GUILHERME HENRIQUE DA SILVA BATISTA', '618', '1094', 'em_dia', 'Thamires'),
  ('MARIA JUNMA DUARTE', '617', '1082', 'em_dia', 'Thamires'),
  ('ED CLAYTON ALVES DE OLIVEIRA', '535', '1031', 'em_dia', 'Thamires'),
  ('LUCIANE CAMPOS CRUVINEL', '617', '7340', 'em_dia', 'Thamires'),
  ('SALVADOR SEVERINO DA SILVA', '618', '4150', 'em_dia', 'Thamires'),
  ('BRUNO DE BRITO SANTOS', '540', '1580', 'em_dia', 'Thamires'),
  ('ANDRE JANDT', '540', '365', 'em_dia', 'Thamires'),
  ('NILTON DO NASCIMENTO RODRIGUES', '617', '3352', 'em_dia', 'Thamires'),
  ('GUSTAVO SOARES BRAGA', '541', '136', 'em_dia', 'Thamires'),
  ('CEZAR AUGUSTO ARAUJO CABRAL', '535', '530', 'em_dia', 'Thamires'),
  ('LUIZ CARLOS DE MELO', '618', '3038', 'em_dia', 'Thamires'),
  ('MARCIO FERREIRA DOS SANTOS', '618', '186', 'em_dia', 'Thamires'),
  ('luiz fernando caetano da silva', '708', '1117', 'em_dia', 'Thamires'),
  ('JEFFERSON MARTINS SANTIAGO', '617', '4377', 'em_dia', 'Thamires'),
  ('CRISTIANO DA CRUZ FLORÊNCIO', '617', '7642', 'em_dia', 'Thamires'),
  ('William Felipe Souza Colasso', '618', '5042', 'em_dia', 'Thamires'),
  ('Erison Lira de Souza', '617', '2284', 'em_dia', 'Thamires'),
  ('RIQUELME RIBEIRO DE SOUZA SILVA', '618', '7050', 'em_dia', 'Thamires'),
  ('LUIZ HENRIQUE BRASSIOLI', '539', '2056', 'em_dia', 'Thamires'),
  ('LEANDRO FERRELI SOUZA', '618', '9417', 'em_dia', 'Thamires'),
  ('FERNANDO FLORENCIO DA MATA', '618', '5695', 'em_dia', 'Thamires'),
  ('Braian Henrique Silva', '618', '2465', 'em_dia', 'Thamires'),
  ('GILSON DE JESUS FERRO RODRIGUES', '617', '6400', 'em_dia', 'Thamires'),
  ('DIEGO APARECIDO MARTINS DOS SANTOS', '617', '4747', 'em_dia', 'Thamires'),
  ('Gustavo naian campos Delgado', '618', '1939', 'em_dia', 'Thamires'),
  ('Allan Vieira Kerheisbaumer', '618', '7691', 'em_dia', 'Thamires'),
  ('EVANILSON CRUZ DOS SANTOS', '618', '6085', 'em_dia', 'Thamires'),
  ('André luiz Samaniego', '540', '1587', 'em_dia', 'Thamires'),
  ('Leonardo de Almeida Biath', '618', '2878', 'em_dia', 'Thamires'),
  ('PAULO BRUNO LOPES DO NASCIMENTO', '617', '3041', 'em_dia', 'Thamires'),
  ('FRANCISCO FABIO DA SILVA LIMA', '617', '5654', 'em_dia', 'Thamires'),
  ('Adriel Silva Oliveira', '618', '8904', 'em_dia', 'Thamires'),
  ('MARCOS ANTONIO DA SILVA', '542', '4069', 'em_dia', 'Thamires'),
  ('Mateus da silva oliveira', '618', '7949', 'em_dia', 'Thamires'),
  ('CARLOS ALBERTO SANTIAGO GOMES', '617', '5506', 'em_dia', 'Thamires'),
  ('jonas batista de sousa', '618', '9728', 'em_dia', 'Thamires'),
  ('Lucas Otávio Rosário Vitor', '617', '3224', 'em_dia', 'Thamires'),
  ('Mateus Martins Messias', '618', '564', 'em_dia', 'Thamires'),
  ('eudes jose tonelli', '619', '3976', 'em_dia', 'Thamires'),
  ('jose antonio sá barreto conceição', '617', '6629', 'em_dia', 'Thamires'),
  ('Matheus rocha jacob', '617', '3775', 'em_dia', 'Thamires'),
  ('diego leao araujo moreno', '461', '2357', 'em_dia', 'Thamires'),
  ('diego leao araujo moreno', '461', '9738', 'em_dia', 'Thamires'),
  ('Raimundo Oliveira Carvalho filho', '461', '2276', 'em_dia', 'Thamires'),
  ('Jefferson Sanches Matela', '618', '6748', 'em_dia', 'Thamires'),
  ('Maxwell Magalhães Cocco', '617', '6327', 'em_dia', 'Cley'),
  ('Rodrigo Lopes de Araújo', '617', '6630', 'em_dia', 'Cley'),
  ('Luigi Moreno Segatto', '617', '3678', 'em_dia', 'Cley'),
  ('silvio antonio machado', '618', '1660', 'em_dia', 'Cley'),
  ('Marcia Aparecida Moraes Santos', '617', '6725', 'em_dia', 'Cley'),
  ('Wellington Alexandre Da Silva', '618', '5992', 'em_dia', 'Cley'),
  ('Marcelo santos machado', '618', '7905', 'em_dia', 'Cley'),
  ('Vinicius Passos da Silva', '617', '5657', 'em_dia', 'Cley'),
  ('DIEGO APARECIDO MARTINS DOS SANTOS', '461', '7982', 'em_dia', 'Cley'),
  ('Melquisedec Pinho dos Santos', '619', '5651', 'em_dia', 'Cley'),
  ('Anderson Buenos da Cruz', '617', '4744', 'em_dia', 'Cley'),
  ('Emerson conceição pacheco', '617', '7363', 'em_dia', 'Cley'),
  ('osmar arini junior', '619', '5745', 'em_dia', 'Cley'),
  ('VINICIUS JUNIO RUIZ', '618', '9346', 'em_dia', 'Cley'),
  ('UILSON CORREIA DO NASCIMENTO', '617', '1966', 'em_dia', 'Cley'),
  ('JÚLIO CÉSAR DOS SANTOS', '617', '3133', 'em_dia', 'Cley'),
  ('MAURI LELIS QUEIROZ JUNIOR', '617', '4983', 'em_dia', 'Cley'),
  ('SILVANA GONÇALVES MEDEIROS', '576', '845', 'em_dia', 'Cley'),
  ('THAMIRES CRISTINA ANTONIO', '618', '6096', 'em_dia', 'Cley'),
  ('lucas pinheiro dos santos', '617', '990', 'em_dia', 'Cley'),
  ('RAIMUNDO ADRIANO FERREIRA ALMEIDA', '617', '4258', 'em_dia', 'Cley'),
  ('LUCILENE SOARES E SILVA LELIS', '619', '8946', 'em_dia', 'Cley'),
  ('MARCELO DA SILVA BERNARDO', '461', '4902', 'em_dia', 'Cley'),
  ('RAPHAEL BARBOSA GOLD', '617', '7657', 'em_dia', 'Cley'),
  ('ERIK DOS SANTOS LIMA', '618', '5050', 'em_dia', 'Cley'),
  ('CARLOS DANIEL BATISTA SILVANO', '461', '2042', 'em_dia', 'Cley'),
  ('JOÃO MARIA DO NASCIMENTO BARROS', '618', '2115', 'em_dia', 'Cley'),
  ('ANDERSON IRENEU DA SILVA', '618', '5333', 'em_dia', 'Cley'),
  ('Almir da Silva', '617', '1099', 'em_dia', 'Cley'),
  ('JAIR SOARES ADORNO', '461', '2809', 'em_dia', 'Cley'),
  ('JAIR SOARES ADORNO', '461', '1102', 'em_dia', 'Cley'),
  ('LEONARDO  FOLGATO CIOFFI', '617', '7045', 'em_dia', 'Cley'),
  ('GABRIEL FARINAZZO GOMES DE OLIVEIRA', '706', '5704', 'em_dia', 'Cley'),
  ('Daiane Dalila Mendonça Sales', '704', '2991', 'em_dia', 'Cley'),
  ('Edmilson Ferreira', '542', '6557', 'em_dia', 'Cley'),
  ('CARLOS EDUARDO APARECIDO DE AQUINO', '617', '2661', 'em_dia', 'Cley'),
  ('PRISCILA CAVALCANTI ALVES', '618', '1141', 'em_dia', 'Cley'),
  ('ANDERSON CLAYTON DE PAULA', '619', '6280', 'em_dia', 'Cley'),
  ('Luís Augusto Barbosa de Almeida', '618', '5607', 'em_dia', 'Cley'),
  ('Tereza Cristina Marques de Brito', '704', '1885', 'em_dia', 'Cley'),
  ('JAIR SOARES ADORNO', '461', '4012', 'em_dia', 'Cley'),
  ('ADRIANA ISABEL DOS SANTOS ARENA', '704', '2472', 'em_dia', 'Cley'),
  ('MAXSUEL SANTOS DA SILVA', '704', '1008', 'em_dia', 'Cley'),
  ('MARCOS VINICIUS GONÇALVES DA SILVA', '618', '2005', 'em_dia', 'Cley'),
  ('raphael braga marques', '617', '802', 'em_dia', 'Cley'),
  ('Vicente Batista de Brito', '704', '898', 'em_dia', 'Cley'),
  ('fabiano pacheco gomes', '575', '83', 'em_dia', 'Cley'),
  ('GILMAR MIRANDA DE BITRO', '617', '2913', 'em_dia', 'Cley'),
  ('ELVIS FREDERICO DE ALMEIDA', '617', '7889', 'em_dia', 'Cley'),
  ('gilva oliveira carvalho', '618', '3585', 'em_dia', 'Cley'),
  ('hernanes da silva santos', '618', '5381', 'em_dia', 'Cley'),
  ('ANDERSON DE SENA SELVAGIO', '538', '6918', 'em_dia', 'Cley'),
  ('JOSE FERNANDES DOS SANTOS', '617', '7895', 'em_dia', 'Cley'),
  ('andre luiz neves dos santos', '617', '3319', 'em_dia', 'Gabriel'),
  ('RODRIGO DE EJSUS SANTANA', '540', '1244', 'em_dia', 'Gabriel'),
  ('erick victor barbosa domingos', '460', '770', 'em_dia', 'Gabriel'),
  ('CLAUDIVAN APARECIDO  NICOLAU', '704', '238', 'em_dia', 'Gabriel'),
  ('Yllana mayumi kuraba maronezi', '529', '1435', 'em_dia', 'Gabriel'),
  ('Wesmey de Souza Santos', '617', '7426', 'em_dia', 'Gabriel'),
  ('Eder Santos Da Silva', '617', '8891', 'em_dia', 'Gabriel'),
  ('JOSE MATEUS DA SILVA', '617', '8392', 'em_dia', 'Gabriel'),
  ('ERIVAN DE SOUSA SILVA FEIJÓ', '542', '8548', 'em_dia', 'Gabriel'),
  ('ISRAEL CORDEIRO DA SILVA', '617', '8864', 'em_dia', 'Gabriel'),
  ('kauã gomes de jesus', '617', '8714', 'em_dia', 'Gabriel'),
  ('Jadson Lima Evangelista', '617', '8817', 'em_dia', 'Gabriel'),
  ('Aldenir Cristiano Araujo', '617', '8902', 'em_dia', 'Gabriel'),
  ('Maísa Aparecida Luiz', '617', '8582', 'em_dia', 'Gabriel'),
  ('Lealdo Costa dos Santos', '575', '826', 'em_dia', 'Gabriel'),
  ('wenderson da Silva Café', '529', '3181', 'em_dia', 'Gabriel'),
  ('GUILHERME HENRIQUE CORREIA LEITE', '618', '8358', 'em_dia', 'Gabriel'),
  ('marcelo soares de brito', '617', '8422', 'em_dia', 'Gabriel'),
  ('JOSÉ RICARDO BARBOSA MEDEIROS', '617', '8889', 'em_dia', 'Gabriel'),
  ('CAMILA CRISTINA DE OLIVEIRA GOMES', '529', '370', 'em_dia', 'Gabriel'),
  ('fernando libanio milhorini', '619', '6326', 'em_dia', 'Gabriel'),
  ('CARLOS ROBERTO DA SILVEIRA DUARTE', '529', '1942', 'em_dia', 'Gabriel'),
  ('EDUARDO FRANCISCO', '542', '4356', 'em_dia', 'Gabriel'),
  ('LUIS HENRIQUE MARTINS DOS REIS', '618', '2401', 'em_dia', 'Gabriel'),
  ('Geovane do Carmo Silva', '617', '4346', 'em_dia', 'Gabriel'),
  ('Gilberto Teodoro da Cunha', '617', '2428', 'em_dia', 'Gabriel'),
  ('Jorge Felipe Vieira lima', '535', '1209', 'em_dia', 'Gabriel'),
  ('WALLACE ALVES BARBOSA', '619', '5177', 'em_dia', 'Gabriel'),
  ('Valdelino ramos  santos', '618', '6884', 'em_dia', 'Gabriel'),
  ('Myqueias lopes Celestino', '618', '4955', 'em_dia', 'Gabriel'),
  ('kleber pinto ribeiro', '618', '3391', 'em_dia', 'Gabriel'),
  ('RODRIGO SOUSA DE ARAÚJO', '618', '8073', 'em_dia', 'Gabriel'),
  ('carlos eduardo santos', '540', '1386', 'em_dia', 'Gabriel'),
  ('Iure de Souza Cruz', '540', '75', 'em_dia', 'Gabriel'),
  ('MARCELO REZENDE FELIX', '533', '787', 'em_dia', 'Gabriel'),
  ('Mário Teixeira Nunes Filho', '617', '6844', 'em_dia', 'Gabriel'),
  ('SIDIANE ZAMBONI', '575', '951', 'em_dia', 'Gabriel'),
  ('fabricio aparecido dos santos', '617', '8634', 'em_dia', 'Gabriel'),
  ('MAÍRA GABRIELE OLIVEIRA DA SILVA', '529', '8853', 'em_dia', 'Gabriel'),
  ('edson roberto ferreira da silva', '618', '3454', 'em_dia', 'Gabriel'),
  ('raimundo nonato alves de sousa', '617', '8594', 'em_dia', 'Gabriel'),
  ('MARCELO SIQUEIRA DOS SANTOS', '619', '936', 'em_dia', 'Gabriel'),
  ('FABIO SANTOS SILVA', '618', '6893', 'em_dia', 'Gabriel'),
  ('Paulo Henrique bench', '618', '2622', 'em_dia', 'Gabriel'),
  ('JULIEZIO PEREIRA ALVES', '531', '725', 'em_dia', 'Gabriel'),
  ('Gabriel Alves Pereira Gandes', '618', '7141', 'em_dia', 'Gabriel'),
  ('PAULA SIMONI ARZE ROCHA VENDITTI', '529', '3083', 'em_dia', 'Gabriel'),
  ('PAULA SIMONI ARZE ROCHA VENDITTI', '617', '8630', 'em_dia', 'Gabriel'),
  ('maykon ulisses da silva', '540', '3108', 'em_dia', 'Gabriel'),
  ('IRINEU AQUILES FERREIRA GOMES', '617', '9079', 'em_dia', 'Gabriel'),
  ('LORIEDSON SALOMAO RIBEIRO DE CASTRO', '540', '3969', 'em_dia', 'Gabriel'),
  ('ELIMAR GOMES DA SILVA', '617', '5860', 'em_dia', 'Gabriel'),
  ('José Amauri Alves da Silva', '618', '88', 'em_dia', 'Thamires'),
  ('BIANCA FARINAZZO GOMES CHAGAS', '706', '5876', 'em_dia', 'Thamires'),
  ('ARIELSON REIS DE SOUZA', '617', '9020', 'em_dia', 'Thamires'),
  ('DEIVISON AUGUSTO DE SOUZA ALVES', '617', '124', 'em_dia', 'Thamires'),
  ('CRISTIANO APARECIDO DOS SANTOS', '617', '8251', 'em_dia', 'Thamires'),
  ('Fernando Vieira de Souza', '618', '950', 'em_dia', 'Thamires'),
  ('Pablo Henrique de Oliveira Santos', '617', '8540', 'em_dia', 'Thamires'),
  ('RICARDO DE MELO FEITOSA', '617', '8462', 'em_dia', 'Thamires'),
  ('Antonio apolinario junior', '617', '8526', 'em_dia', 'Thamires'),
  ('CAIO PATRICK PEREIRA', '540', '2092', 'em_dia', 'Thamires'),
  ('EDINILDO MAIA COSTA', '617', '8236', 'em_dia', 'Thamires'),
  ('gabriel victor jacintho silva', '460', '824', 'em_dia', 'Thamires'),
  ('RYAN GOUDINHO MARQUES', '465', '227', 'em_dia', 'Thamires'),
  ('GILVAN RODRIGUES DE SOUSA', '539', '5636', 'em_dia', 'Thamires'),
  ('FRANCISCO CANTARELE VICENTE', '617', '6199', 'em_dia', 'Thamires'),
  ('EDER CAMBRUZZI', '535', '4065', 'em_dia', 'Thamires'),
  ('Rômulo de Souza Navega da Silva', '617', '6992', 'em_dia', 'Thamires'),
  ('Carlos Eduardo Silva Pinto', '617', '9195', 'em_dia', 'Thamires'),
  ('Vagner Luis Brile', '618', '9988', 'em_dia', 'Thamires'),
  ('ARQUIMEDES CARDOSO DE OLIVEIRA JUNIOR', '540', '464', 'em_dia', 'Thamires'),
  ('MARCIO CABRAL MACHADO', '617', '8620', 'em_dia', 'Thamires'),
  ('Thiago dos Santos Martins', '535', '4715', 'em_dia', 'Thamires'),
  ('sergio Moreira ferreira', '617', '1023', 'em_dia', 'Thamires'),
  ('ANTONIO CARLOS ALVES DE SOUZA FILHO', '618', '4118', 'em_dia', 'Thamires'),
  ('ELIVALDO OLIVEIRA ARRUDA', '618', '4157', 'em_dia', 'Thamires'),
  ('BRENO RENATO ALVES CAMPOS', '616', '1243', 'em_dia', 'Thamires'),
  ('ARGEL FERREIRA DA SILVA', '618', '3491', 'em_dia', 'Thamires'),
  ('jose hilario de s hernandes martin junior', '618', '8469', 'em_dia', 'Thamires'),
  ('Urbano Manoel de Oliveira', '616', '597', 'em_dia', 'Thamires'),
  ('JOSUE RIBEIRO DOS SANTOS FILHO', '540', '1210', 'em_dia', 'Thamires'),
  ('Rodrigo Donelli Garcia', '576', '470', 'em_dia', 'Thamires'),
  ('Leandro José Alves', '617', '7453', 'em_dia', 'Thamires'),
  ('Thiago Henrique Francisco Quintiliano', '618', '9132', 'em_dia', 'Thamires'),
  ('UELITON DOS SANTOS MAGALDI', '618', '8534', 'em_dia', 'Thamires'),
  ('ALEXSANDER MUNIZ DE CARVALHO', '533', '1199', 'em_dia', 'Thamires'),
  ('CAIO AUGUSTUS BERENGAN', '535', '4281', 'em_dia', 'Thamires'),
  ('SERGIO NOGUEIRA', '617', '8644', 'em_dia', 'Thamires'),
  ('Almir Messias', '617', '8882', 'em_dia', 'Thamires'),
  ('RUAN SILAS DE MEIRELES SANTOS', '535', '1406', 'em_dia', 'Thamires'),
  ('RENATO GANZERT', '616', '612', 'em_dia', 'Thamires'),
  ('RENATO GANZERT', '616', '341', 'em_dia', 'Thamires'),
  ('joao henrique soares gaioski', '616', '21', 'em_dia', 'Thamires'),
  ('Felipe Silva Moura Brasil', '5000', '3890', 'em_dia', 'Thamires'),
  ('MANOEL DE JESUS SANTOS', '618', '3933', 'em_dia', 'Thamires'),
  ('Alberto Vieira dos Santos', '5000', '2121', 'em_dia', 'Thamires'),
  ('BRUNO RODRIGUES BARBOSA DIAS CARDOSO', '616', '578', 'em_dia', 'Thamires'),
  ('Murilo Mozart de Souza Pereira', '535', '3448', 'em_dia', 'Thamires'),
  ('Rogério Soares Dos Santos', '617', '6278', 'em_dia', 'Thamires'),
  ('LUCIANO DO NASCIMENTO GOMES', '542', '9202', 'em_dia', 'Thamires'),
  ('André Luiz Fernandes Gomes', '617', '2453', 'em_dia', 'Thamires'),
  ('RODRIGO APARECIDO  DE PONTES', '617', '8896', 'em_dia', 'Thamires'),
  ('Gelson Branco De Moraes Junior', '540', '1331', 'em_dia', 'Thamires'),
  ('ICARO MATHEUS AMARO MONTEIRO', '617', '8218', 'em_dia', 'Cley'),
  ('JOÃO VICTOR DE OLIVEIRA SOUZA', '617', '5686', 'em_dia', 'Cley'),
  ('FABIANO GALVÃO DE SOUZA', '617', '3642', 'em_dia', 'Cley'),
  ('Cicero da silva lourenço', '617', '8650', 'em_dia', 'Cley'),
  ('JOSE ALCIRLEY DA SILVA', '538', '1054', 'em_dia', 'Cley'),
  ('Júlio Cesar rego', '617', '8056', 'em_dia', 'Cley'),
  ('jackson carlos lopes dos santos', '617', '5156', 'em_dia', 'Cley'),
  ('Vinicius Kaike Anastácio Rodrigues', '539', '7073', 'em_dia', 'Cley'),
  ('MILENA JUNQUEIRA DAVID', '617', '8823', 'em_dia', 'Cley'),
  ('Francisley Gonçalves Ferreira', '618', '7350', 'em_dia', 'Cley'),
  ('Ismael Soares dos Santos', '617', '8364', 'em_dia', 'Cley'),
  ('LEONARDO RAFAEL BITTAR', '617', '268', 'em_dia', 'Cley'),
  ('MARIA ANDRESSA MENDES DE BRITO', '618', '677', 'em_dia', 'Cley'),
  ('MARCOS ANTONIO DE CARVALHO', '535', '4345', 'em_dia', 'Cley'),
  ('VINICIUS WINKLER MOTA', '617', '5909', 'em_dia', 'Cley'),
  ('SIDNEY ALVES TAVARES', '617', '8965', 'em_dia', 'Cley'),
  ('Igor Pereira dos Santos', '706', '9439', 'em_dia', 'Cley'),
  ('SABRINA MARIA DE ARAGÃO BULCÃO', '535', '4722', 'em_dia', 'Cley'),
  ('jose luiz dos santos', '617', '7745', 'em_dia', 'Cley'),
  ('NATALY FERREIRA RODRIGUES', '542', '9754', 'em_dia', 'Cley'),
  ('Isabella Meneses de Queiroz Marques Vilar', '539', '2550', 'em_dia', 'Cley'),
  ('Agnaldo Jose de Almeida', '616', '435', 'em_dia', 'Cley'),
  ('LEVI LUCAS DA SILVA', '617', '2028', 'em_dia', 'Cley'),
  ('IGOR BONFIM P DE SOUZA', '616', '207', 'em_dia', 'Cley'),
  ('Joao Batista de Assis', '540', '1898', 'em_dia', 'Cley'),
  ('RAFAEL ANTONIO RONDON GUATARASMA', '533', '1034', 'em_dia', 'Cley'),
  ('FRANCILDO RODRIGUES DE SOUZA', '542', '8454', 'em_dia', 'Cley'),
  ('ROBSON FEITOSA PIMENTEL', '533', '1069', 'em_dia', 'Cley'),
  ('joao vitor oliveira lyrio', '576', '465', 'em_dia', 'Cley'),
  ('ERICLES FERREIRA DE MEDEIROS', '529', '4619', 'em_dia', 'Cley'),
  ('VICTOR DE OLIVEIRA SANTOS', '466', '171', 'em_dia', 'Cley'),
  ('Jonathan Sandro', '618', '3760', 'em_dia', 'Cley'),
  ('Edvaldo Antônio da Silva', '617', '4754', 'em_dia', 'Cley'),
  ('JOAO CARLOS FERRO RIBEIRO', '616', '1145', 'em_dia', 'Cley'),
  ('carlos alberto serafim dos anjos', '540', '626', 'em_dia', 'Cley'),
  ('JUNER FONSECA DE SOUZA', '539', '3259', 'em_dia', 'Cley'),
  ('BRENO NUNES MEDONCA', '617', '2146', 'em_dia', 'Cley'),
  ('FERNANDO CASSIANO', '618', '8029', 'em_dia', 'Cley'),
  ('MAURÍCIO RIBEIRO DE OLIVEIRA', '539', '337', 'em_dia', 'Cley'),
  ('Cláudio Hilário de Souza', '618', '2229', 'em_dia', 'Cley'),
  ('RAFAEL AFONSO DA SILVA', '7001', '5561', 'em_dia', 'Cley'),
  ('bruno moreira de oliveira', '533', '1401', 'em_dia', 'Cley'),
  ('marcos stefan cavalheiro', '535', '4706', 'em_dia', 'Cley'),
  ('LORIEDSON SALOMAO RIBEIRO DE CASTRO', '529', '9515', 'em_dia', 'Cley'),
  ('rodrigo foresto piasentin', '618', '8786', 'em_dia', 'Cley'),
  ('THIAGO GARCIA SANTIAGO', '463', '5465', 'em_dia', 'Cley'),
  ('Jakson Silva Rocha', '7001', '1514', 'em_dia', 'Cley'),
  ('jackson carlos tiburcio nunes', '7001', '1837', 'em_dia', 'Cley'),
  ('RENATO DO VALE', '540', '2766', 'em_dia', 'Cley'),
  ('Daniel Henrique Costa Santos', '463', '1475', 'em_dia', 'Cley'),
  ('LUAN ITALO BERNARDINO FRAZÃO', '576', '422', 'em_dia', 'Cley'),
  ('William da Cruz', '617', '3049', 'em_dia', 'Cley')
) as v(nome, grupo, cota, status, responsavel)
join resp on resp.nome = v.responsavel;
